version: "3.7"

services:
  mongo:
    image: mongo
    container_name: mongodb-1
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mongo-ui:
    image: mongo-express
    container_name: mongo-ui-1
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    ports:
      - 8001:8081

volumes:
  mongo: