version: "3.7"

services:
  mongo:
    image: mongo
    container_name: zebtro-db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpassword
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/db

  mongo-ui:
    image: mongo-express
    container_name: mongo-ui-1
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpassword
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
    ports:
      - 8001:8081
    depends_on: 
      - mongo

  app:
    image: akshit8/zebtro-server
    container_name: zebtro-app
    restart: always
    environment:
      MONGO_URI: mongodb://mongo:27017/
    ports:
      - 3000:3000
    depends_on:
     - mongo

  logger:
    container_name: fluentd
    user: root
    image: fluent/fluentd:v1.11-debian
    volumes:
    - /var/lib/docker/containers:/fluentd/log/containers
    - ./fluent.conf:/fluentd/etc/fluent.conf
    - ./logs:/output/
    logging:
      driver: "local"

volumes:
  mongo: