name: CI

on:
  workflow_dispatch

jobs:
  ci:
    name: CI job
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: rootpassword
        ports:
          - 27017:27017

    steps:
    - name: checkout
      uses: actions/checkout@v2
    
    - name: setup node
      uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: format and lint
      run: |
        npm run format
        npm run lint

    - name: test
      run: |
        npm run test

    - name: build
      run: |
        npm run build



